# Generated by Django 3.2.5 on 2021-08-11 22:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_cursos_lenguaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='lecciones',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
